___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [2]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [11]:
print(np.__version__)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
None


Створити вектор з 10 елементів, заповнений одиницями:

In [13]:
ones_vector = np.ones(10)
ones_vector

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Створити вектор із значеннями від 0 до 10:

In [15]:
range_vector = np.array(range(11))
range_vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Створити матрицю 5 на 5, заповнену нулями:

In [17]:
zero_matrix = np.zeros((5,5),)
zero_matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [23]:
random_vector = np.random.randint(-100,100,20,)
print('Vector:', random_vector)
non_zero_elements = np.nonzero(random_vector)
print('Non-zero elements are located at:', non_zero_elements)

Vector: [ 88 -15 -12 -37  63 -40  -2 -65 -40 -38  56  46  63 -11 -42  33 -91  25
 -27 -80]
Non-zero elements are located at: (array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19]),)


Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [24]:
mean_value = np.mean(random_vector)
print('Середнє значення:', mean_value)

median_value = np.median(random_vector)
print('Медіана:', median_value)

stand_dev_value = np.std(random_vector)
print('Стандартне відхилення:', stand_dev_value)

Середнє значення: -6.3
Медіана: -13.5
Стандартне відхилення: 49.879955894126454


Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [5]:
rand_matrix_1 = np.random.randint(0,10,(4,2),)
print('Matrix #1')
print(rand_matrix_1)
print()

rand_matrix_2 = np.random.randint(0,10,(2,2),)
print('Matrix #2')
print(rand_matrix_2)
print()
print('Product of 2 matrices')
matrices_product = np.dot(rand_matrix_1,rand_matrix_2)
print(matrices_product)

Matrix #1
[[6 2]
 [7 7]
 [0 8]
 [9 8]]

Matrix #2
[[5 2]
 [2 1]]

Product of 2 matrices
[[34 14]
 [49 21]
 [16  8]
 [61 26]]


Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [18]:
print('Matrix to vector:')
matrix_to_vector = np.reshape(matrices_product,(1,matrices_product.size))
print(matrix_to_vector)

print()

print('Max:', np.max(matrix_to_vector))
vector_min = np.min(matrix_to_vector)
print('Min:', vector_min)

print()

print("Substitute min element with 0:")
matrix_to_vector[matrix_to_vector==vector_min]=0
print(matrix_to_vector)

Matrix to vector:
[[34 14 49 21 16  8 61 26]]

Max: 61
Min: 8

Substitute min element with 0:
[[34 14 49 21 16  0 61 26]]


Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [17]:
print(np.corrcoef(matrices_product)) #всі пари
print()
print(np.corrcoef(matrices_product[0]), np.corrcoef(matrices_product[1]))
print()
print(np.corrcoef(matrices_product[0]), np.corrcoef(matrices_product[2]))
print()
print(np.corrcoef(matrices_product[0]), np.corrcoef(matrices_product[3]))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

1.0 1.0

1.0 1.0

1.0 1.0


Дано матрицю. Знайти ранг матриці:

In [21]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])

r = np.linalg.matrix_rank(a)
r

3

Знайти визначник матриці:

In [22]:
d = np.linalg.det(a)
d

440.0000000000002

Знайти власні значення та власні вектори матриці: 

In [25]:
vals, vects = np.linalg.eig(a)
print(vals)
print()
print(vects)

[14.13520334+0.j         -4.56760167+3.20389947j -4.56760167-3.20389947j]

[[ 0.43131913+0.j         -0.31386258-0.47450898j -0.31386258+0.47450898j]
 [ 0.41502436+0.j         -0.07049527+0.4090732j  -0.07049527-0.4090732j ]
 [ 0.8010734 +0.j          0.7099444 +0.j          0.7099444 -0.j        ]]


array([14.13520334+0.j        , -4.56760167+3.20389947j,
       -4.56760167-3.20389947j])

Знайдіть число, що найчастіше зустрічається в масиві:

In [38]:
a = np.random.randint(0,10,50)

#Method 1: using np.unique with parameter return_counts = True
# Returns: vals - unique values, counts - how many times value occurs in array

vals, counts = np.unique(a, return_counts=True)
print('Most frequent element is:', vals[counts.argmax()])  #argmax - returns index of max element


Most frequent element is: 6


Виведіть лише парні числа, що діляться на 5:

In [49]:
a = np.random.randint(0,10,50)
print(a)
b = a[(a%2==0)&(a%5==0)&(a!=0)]

if len(b)==0:
    print('No values found!')

[3 0 3 6 0 0 6 2 0 9 2 5 3 0 3 7 2 9 2 2 1 9 7 2 0 8 0 3 6 6 6 0 2 6 5 2 2
 4 4 8 5 2 3 3 3 0 4 0 2 2]
No values found!


Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [51]:
a = np.array([[2, 5],[1, -10]])
b = np.array([1,3])

solution = np.linalg.solve(a,b)
print(solution)

[ 1.  -0.2]
